name: Generate release

on:
  release:
    types: published

env:
  DOC_HTML_DIR: build/html
  DOC_ARTIFACT: pool-day-doc

jobs:
  build:
    name: Build library
    runs-on: ubuntu-latest
    container:
      image: andrelcmoreira/pool-day:v2
      volumes:
        - ${{ github.workspace }}:/pool-day
      credentials:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    steps:
      - uses: actions/checkout@v2
      - name: Build library
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -S . -B build
          cmake --build build --target install

  generate_doc:
    name: Generate documentation
    runs-on: ubuntu-latest
    container:
      image: andrelcmoreira/pool-day:v1
      volumes:
        - ${{ github.workspace }}:/pool-day
      credentials:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    steps:
      - uses: actions/checkout@v2
      - name: Build library doc
        run: |
          cmake -DBUILD_DOCUMENTATION=ON -S . -B build
          cmake --build build

      - name: Create doc tarball
        run: tar -C ${{ env.DOC_HTML_DIR }} -czf ${{ env.DOC_ARTIFACT }}.tar.gz .

      - name: Upload doc to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.DOC_ARTIFACT }}.tar.gz
          asset_name: ${{ env.DOC_ARTIFACT }}-${{ github.ref_name }}.tar.gz
          tag: ${{ github.ref_name }}
          overwrite: true
